p8105_hw1_al4925
================
Angela Lin
2025-09-20

## Problem 1

``` r
library(moderndive)
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.2     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   4.0.0     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.1     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
data("early_january_weather")
names(early_january_weather)
```

    ##  [1] "origin"     "year"       "month"      "day"        "hour"      
    ##  [6] "temp"       "dewp"       "humid"      "wind_dir"   "wind_speed"
    ## [11] "wind_gust"  "precip"     "pressure"   "visib"      "time_hour"

``` r
nrow(early_january_weather)
```

    ## [1] 358

``` r
ncol(early_january_weather)
```

    ## [1] 15

``` r
mean(early_january_weather$temp, na.rm = TRUE)
```

    ## [1] 39.58212

The “early_january_weather” records hourly meteorological data for LGA,
JFK and EWR for the month of January 2013. This is a subset of the
weather data frame from nycflights13. This dataser contains 358 rows
representing hourly measuremnets and 15 variables. The variables
includes origin, year, month, day, hour, temperature, dewpoint in
Fahrenheit, humid, wind direction (in degrees), speed and gust speed (in
degree), precipiation in inches, pressure in millibars, visibility in
miles, and the recording date and hour. Overall, the mean temperature is
around 39.58 F.

``` r
temp_plot<- ggplot(early_january_weather, aes(x = time_hour, y = temp)) +
  geom_point(aes(color = humid)) +
  labs(title = "NYC Temperature vs Time in Early January 2013",
       x = "Time", 
       y = "Temperature",
       color = "Humidity")
temp_plot
```

![](p8105_hw1_4925_files/figure-gfm/unnamed-chunk-2-1.png)<!-- -->

``` r
ggsave("ggp_temp.pdf", temp_plot, width = 8, height = 5 )
```

In early January 2013, the temperature started in the 30 to low 40 F,
and it climbed to mid-50 F, then drop again. While the temperature is
overall growing, there is a daily wiggle, which may be cooler at
night/morning and warmer in the afternoon. The lighter dots represents
higher humidity during the warm stretch, while the darker dots
represents the cooler hour with the lower humidity. Generally, the
warmer periods tends to be more humid, but humidity could change due to
the daily temperature wiggling.

## Problem 2

``` r
number<- rnorm(10)
logical<- number > 0
character<- letters[1:10]
factor<- factor(rep(c("low", "medium", "high"), levels = c("low", "medium", "high"), length = 10))

df<- tibble(number, logical, character, factor)
df
```

    ## # A tibble: 10 × 4
    ##     number logical character factor
    ##      <dbl> <lgl>   <chr>     <fct> 
    ##  1  0.778  TRUE    a         low   
    ##  2 -0.0252 FALSE   b         medium
    ##  3  1.23   TRUE    c         high  
    ##  4  0.942  TRUE    d         low   
    ##  5  0.776  TRUE    e         medium
    ##  6  0.355  TRUE    f         high  
    ##  7 -0.184  FALSE   g         low   
    ##  8  1.97   TRUE    h         medium
    ##  9 -0.559  FALSE   i         high  
    ## 10 -0.103  FALSE   j         low

``` r
mean(df$number)
```

    ## [1] 0.5185629

``` r
mean(df$logical)
```

    ## [1] 0.6

``` r
mean(df$character)
```

    ## Warning in mean.default(df$character): argument is not numeric or logical:
    ## returning NA

    ## [1] NA

``` r
mean(df$factor)
```

    ## Warning in mean.default(df$factor): argument is not numeric or logical:
    ## returning NA

    ## [1] NA

In this case, mean works in `number` because it is numeric. Mean works
in `logical` because R defines `TRUE` as 1 and `FALSE` as 0. Therefore,
the mean is the proportion of the `TRUE`. Mean does not work in
`character` because they are not numeric, and it returns `NA`. Mean also
does not work in `factor` because they are categorical, and it returns
`NA` as well.

``` r
as.numeric(df$number)
```

    ##  [1]  0.77799367 -0.02515347  1.23152626  0.94244514  0.77619826  0.35503495
    ##  [7] -0.18437014  1.97362972 -0.55871081 -0.10296467

``` r
as.numeric(df$logical)
```

    ##  [1] 1 0 1 1 1 1 0 1 0 0

``` r
as.numeric(df$character)
```

    ## Warning: NAs introduced by coercion

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(df$factor)
```

    ##  [1] 2 3 1 2 3 1 2 3 1 2

Now, we apply `as.numeric()` function to each variables. `number`
remains unchanged because they are originally numeric. `logical` changes
from `TURE`/`FALSE` to 1/0. `character` returns `NA` because they are
not numeric or ordered by levels. `factor` returns 1 to 3, aligning with
the levels from “low”, “medium”, and “high”, which given the level order
we set in the origical code. Among four variables, `as.numeric()`
explains why `logical` can get a mean even though they don’t “look
numeric”. It is all because R set `TRUE` to 1 and `FALSE` to 0. And
`factor` can only get the mean if we use `as.numeric()` function to
change their levels into numeric order.
